version: '3.8'

services:

  db:
    image: mysql:8

    container_name: ecommerce_db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce

    ports:
      - "3306:3306"

    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: